allowBuilds:
  '@nestjs/core': true
  '@openapitools/openapi-generator-cli': true
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  inferno: true
  less: true
  lmdb: true
  msgpackr-extract: true
  nx: true
  protobufjs: true
  puppeteer: true
  unrs-resolver: true
  utf-8-validate: true
autoInstallPeers: false
lockfileIncludeTarballUrl: false
minimumReleaseAge: 4320
