allowBuilds:
  '@nestjs/core': true
  '@openapitools/openapi-generator-cli': true
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  inferno: true
  less: true
  lmdb: true
  msgpackr-extract: true
  nx: true
  protobufjs: true
  puppeteer: true
  unrs-resolver: true
  utf-8-validate: true
autoInstallPeers: false
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  # Renovate security update: @nestjs/core@11.1.18
  - "@nestjs/core@11.1.18"
  # Renovate security update: axios@1.15.2
  - axios@1.15.2
  # Renovate security update: svgo@4.0.1 || 4.0.2
  - svgo@4.0.1 || 4.0.2
  # Renovate security update: vite@7.3.2 || 7.3.5
  - vite@7.3.2 || 7.3.5
  # Renovate security update: @opentelemetry/auto-instrumentations-node@0.75.0
  - "@opentelemetry/auto-instrumentations-node@0.75.0"
  # Renovate security update: webpack-dev-server@5.2.6
  - webpack-dev-server@5.2.6
  # Renovate security update: @angular/compiler@20.3.27
  - "@angular/compiler@20.3.27"
  # Renovate security update: @angular/common@20.3.27
  - "@angular/common@20.3.27"
  # Renovate security update: @angular/core@20.3.27
  - "@angular/core@20.3.27"
  # Renovate security update: form-data@4.0.6
  - form-data@4.0.6
  # Renovate security update: nx@22.7.7
  - nx@22.7.7
