name: "Build App"
description: "Lints and builds the frontend and server applications"

runs:
  using: "composite"
  steps:
    - name: Lint
      shell: bash
      run: ./node_modules/.bin/nx run-many --target=lint --all --parallel --maxParallel=4

    - name: Build server and frontend
      shell: bash
      run: |
        ./node_modules/.bin/nx run-many \
          --target=build \
          --projects=server,frontend \
          --parallel \
          --maxParallel=2 \
          --configuration=production

    - name: Compress frontend assets
      shell: bash
      run: ./node_modules/.bin/gzipper compress ./dist/apps/frontend --brotli --gzip
